apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: dap-tas-journey-observability-projects
spec:
  type: url
  targets:
    - https://github.com/loggregator/backstage-files/blob/master/azure-nozzle.yml
    - ./bosh-system-metrics-forwarder.yml