apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: dap-tas-journey-observability-projects
spec:
  owner: dap-tas-journey-observability
  type: url
  targets:
    - ./teams/dap-tas-journey-observability.yml
    - ./systems/logging-and-metrics.yml
    - ./systems/autoscaling.yml
    - ./components/azure-nozzle.yml
    - ./components/bosh-system-metrics-forwarder.yml
    - ./components/bosh-system-metrics-server-release.yml
    - ./components/cf-autoscaling-release.yml
    - ./components/event-log-release.yml
    - ./components/log-cache-cli.yml
    - ./components/log-cache-release.yml
    - ./components/loggregator-agent-release.yml
    - ./components/loggregator-release.yml
    - ./components/metric-registrar-cli.yml
    - https://github.com/pivotal-cf/metric-registrar-release/edit/backstage/catalog/catalog-info.yaml
    - ./components/metrics-discovery-release.yml
    - ./components/service-metrics-release.yml
    - ./components/statsd-injector-release.yml
    - ./components/syslog-release.yml
    - ./components/system-metrics-release.yml
    - ./components/system-metrics-scraper-release.yml