apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: log-cache-release
  description: Provides an in memory caching layer for logs and metrics
  annotations:
    github.com/project-slug: cloudfoundry/log-cache-release
    backstage.io/code-coverage: scm-only
  tags:
    - go
  links:
    - url: https://ci.funtime.lol/teams/loggregator/pipelines/log-cache-release
      title: CI Pipeline
      icon: concourse
      type: ci
spec:
  type: service
  lifecycle: production
  owner: dap-tas-journey-observability
  system: logging-and-metrics