apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: loggregator-agent-release
  description: A collection of composable agents used for interacting with Loggregator and Syslog
  annotations:
    github.com/project-slug: cloudfoundry/loggregator-agent-release
    backstage.io/code-coverage: scm-only
  tags:
    - go
  links:
    - url: https://ci.funtime.lol/teams/loggregator/pipelines/loggregator-agent-release
      title: CI Pipeline
      icon: concourse
      type: ci
spec:
  type: service
  lifecycle: production
  owner: dap-tas-journey-observability
  system: logging-and-metrics