apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-metrics-release
  description: Service Metrics BOSH Release
  annotations:
    github.com/project-slug: cloudfoundry/service-metrics-release
    backstage.io/code-coverage: scm-only
  tags:
    - go
  links:
    - url: https://ci.funtime.lol/teams/loggregator/pipelines/service-metrics-release
      title: CI Pipeline
      icon: concourse
      type: ci
spec:
  type: service
  lifecycle: production
  owner: dap-tas-journey-observability
  system: logging-and-metrics