apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: system-metrics-scraper-release
  description: Components required to collect system metrics from BOSH-deployed vms running the system-metrics-agent
  annotations:
    github.com/project-slug: cloudfoundry/system-metrics-scraper-release
    backstage.io/code-coverage: scm-only
  tags:
    - go
  links:
    - url: https://ci.funtime.lol/teams/loggregator/pipelines/system-metrics-scraper-release
      title: CI Pipeline
      icon: concourse
      type: ci
spec:
  type: service
  lifecycle: production
  owner: dap-tas-journey-observability
  system: logging-and-metrics