apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: count-cores
  description: Counting physical cores used by bosh instance groups
  annotations:
    github.com/project-slug: pivotal/count-cores
    backstage.io/code-coverage: scm-only
  tags:
    - go
  links:
    - url: https://ci.funtime.lol/teams/loggregator/pipelines/count-cores
      title: CI Pipeline
      icon: concourse
      type: ci
spec:
  type: service
  lifecycle: production
  owner: dap-tas-journey-observability
  system: tas-telemetry