apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: metric-registrar-release
  description: Native event and metric envelopes on loggregator
  annotations:
    github.com/project-slug: pivotal-cf/metric-registrar-release
    backstage.io/code-coverage: scm-only
  tags:
    - go
  links:
    - url: https://ci.funtime.lol/teams/loggregator/pipelines/metric-registrar-release
      title: CI Pipeline
      icon: concourse
      type: ci
spec:
  type: service
  lifecycle: production
  owner: dap-tas-journey-observability
  system: logging-and-metrics